### ISSUE TITLE
Error occurred when editing trip with possible index error leading to it

### ISSUE THREAD

**Issue by ShawnTanzc** [AY2021S1-CS2113T-W11-2/tp#129] opened 2020-11-07 17:19 UTC
![image](https://user-images.githubusercontent.com/60372589/98447516-4dc0f380-2160-11eb-89a1-c7db76f55dd7.png)

Take note of the highlight part

![image](https://user-images.githubusercontent.com/60372589/98447664-9d53ef00-2161-11eb-9ef2-bbe9240e5c97.png)

similar problem for delete trip. 

Will you be removing that line?

**Comment by ShawnTanzc** [comment] 2020-11-07 17:21
occured -> occurred as well

**Comment by ivanderjmw** [comment] 2020-11-08 10:23
Hello @ShawnTanzc ,

I was unable to reproduce this error. Could you give me a screenshot of your files inside the `trippie_data` directory, as well as the contents of your `trippie.txt`?

Deleting the directory might fix the problem. Update me! Will fix the typo issue though, thanks for pointing that out.

**Comment by ShawnTanzc** [comment] 2020-11-08 10:59
Hi! Ivander,
Heres the trippie data from the initial test as the issue above
![image](https://user-images.githubusercontent.com/60372589/98462941-ca041700-21f2-11eb-9582-d984e4983827.png)

I tried to replicated the issues and typed as similar as i have tested:
Part 1:
![image](https://user-images.githubusercontent.com/60372589/98463056-9675bc80-21f3-11eb-9911-39a51d0d9313.png)
Part 2:
![image](https://user-images.githubusercontent.com/60372589/98463064-a392ab80-21f3-11eb-9aef-e12d5db27d82.png)
Exited and Part 3:
![image](https://user-images.githubusercontent.com/60372589/98463085-d6d53a80-21f3-11eb-956a-617c3d5fafb0.png)
Delete trip show the same issue as well
![image](https://user-images.githubusercontent.com/60372589/98463155-45b29380-21f4-11eb-8087-41f785735f47.png)

You can try as follows 
Here is my new trippie_data, apparently it doesnt delete from here by itself so... i not sure if we can do anything about it
![image](https://user-images.githubusercontent.com/60372589/98463177-64b12580-21f4-11eb-8233-5a6f8643d1c7.png)

**Comment by ivanderjmw** [comment] 2020-11-08 11:16
Hello Shawn!

It turns out that the problem presists in Windows due to file permission errors.
We have found this as the source of issue. https://stackoverflow.com/questions/40706380/failed-to-delete-a-file-in-windows-using-java.

Thank you for reporting this!

**Comment by ivanderjmw** [comment] 2020-11-08 12:17
This has been resolved in #139

**Closed** 2020-11-08 14:21 UTC
Labels: Priority.High, severity.High
